[package]
name = "hyper-server-faster"
version = "0.1.0"
authors = ["HideakiImamura <gohome.x105.gn@gmail.com>"]

[dependencies]
hyper = "0.11.7"
futures = "0.1.17"
net2 = "0.2.31"
tokio-core = "0.1.10"
num_cpus = "1.0"
